database:
  psql:
    type: psql
    host: localhost
    port: 5432
    user: postgres
    password: root
    name: postgres
    sslmode: disable
  mongo:
    uri: mongodb://localhost:27017
  mysql:
    uri: root:root@tcp(localhost:3306)/discount_service?parseTime=true
server:
  port: 9000
