// Code generated by SQLBoiler 4.4.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("Discounts", testDiscounts)
	t.Run("DiscountAttributes", testDiscountAttributes)
	t.Run("DiscountMetaAttributes", testDiscountMetaAttributes)
}

func TestDelete(t *testing.T) {
	t.Run("Discounts", testDiscountsDelete)
	t.Run("DiscountAttributes", testDiscountAttributesDelete)
	t.Run("DiscountMetaAttributes", testDiscountMetaAttributesDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("Discounts", testDiscountsQueryDeleteAll)
	t.Run("DiscountAttributes", testDiscountAttributesQueryDeleteAll)
	t.Run("DiscountMetaAttributes", testDiscountMetaAttributesQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("Discounts", testDiscountsSliceDeleteAll)
	t.Run("DiscountAttributes", testDiscountAttributesSliceDeleteAll)
	t.Run("DiscountMetaAttributes", testDiscountMetaAttributesSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("Discounts", testDiscountsExists)
	t.Run("DiscountAttributes", testDiscountAttributesExists)
	t.Run("DiscountMetaAttributes", testDiscountMetaAttributesExists)
}

func TestFind(t *testing.T) {
	t.Run("Discounts", testDiscountsFind)
	t.Run("DiscountAttributes", testDiscountAttributesFind)
	t.Run("DiscountMetaAttributes", testDiscountMetaAttributesFind)
}

func TestBind(t *testing.T) {
	t.Run("Discounts", testDiscountsBind)
	t.Run("DiscountAttributes", testDiscountAttributesBind)
	t.Run("DiscountMetaAttributes", testDiscountMetaAttributesBind)
}

func TestOne(t *testing.T) {
	t.Run("Discounts", testDiscountsOne)
	t.Run("DiscountAttributes", testDiscountAttributesOne)
	t.Run("DiscountMetaAttributes", testDiscountMetaAttributesOne)
}

func TestAll(t *testing.T) {
	t.Run("Discounts", testDiscountsAll)
	t.Run("DiscountAttributes", testDiscountAttributesAll)
	t.Run("DiscountMetaAttributes", testDiscountMetaAttributesAll)
}

func TestCount(t *testing.T) {
	t.Run("Discounts", testDiscountsCount)
	t.Run("DiscountAttributes", testDiscountAttributesCount)
	t.Run("DiscountMetaAttributes", testDiscountMetaAttributesCount)
}

func TestHooks(t *testing.T) {
	t.Run("Discounts", testDiscountsHooks)
	t.Run("DiscountAttributes", testDiscountAttributesHooks)
	t.Run("DiscountMetaAttributes", testDiscountMetaAttributesHooks)
}

func TestInsert(t *testing.T) {
	t.Run("Discounts", testDiscountsInsert)
	t.Run("Discounts", testDiscountsInsertWhitelist)
	t.Run("DiscountAttributes", testDiscountAttributesInsert)
	t.Run("DiscountAttributes", testDiscountAttributesInsertWhitelist)
	t.Run("DiscountMetaAttributes", testDiscountMetaAttributesInsert)
	t.Run("DiscountMetaAttributes", testDiscountMetaAttributesInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("DiscountAttributeToDiscountUsingDiscount", testDiscountAttributeToOneDiscountUsingDiscount)
	t.Run("DiscountMetaAttributeToDiscountAttributeUsingDiscountAttribute", testDiscountMetaAttributeToOneDiscountAttributeUsingDiscountAttribute)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("DiscountToDiscountAttributes", testDiscountToManyDiscountAttributes)
	t.Run("DiscountAttributeToDiscountMetaAttributes", testDiscountAttributeToManyDiscountMetaAttributes)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("DiscountAttributeToDiscountUsingDiscountAttributes", testDiscountAttributeToOneSetOpDiscountUsingDiscount)
	t.Run("DiscountMetaAttributeToDiscountAttributeUsingDiscountMetaAttributes", testDiscountMetaAttributeToOneSetOpDiscountAttributeUsingDiscountAttribute)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {
	t.Run("DiscountAttributeToDiscountUsingDiscountAttributes", testDiscountAttributeToOneRemoveOpDiscountUsingDiscount)
	t.Run("DiscountMetaAttributeToDiscountAttributeUsingDiscountMetaAttributes", testDiscountMetaAttributeToOneRemoveOpDiscountAttributeUsingDiscountAttribute)
}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("DiscountToDiscountAttributes", testDiscountToManyAddOpDiscountAttributes)
	t.Run("DiscountAttributeToDiscountMetaAttributes", testDiscountAttributeToManyAddOpDiscountMetaAttributes)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {
	t.Run("DiscountToDiscountAttributes", testDiscountToManySetOpDiscountAttributes)
	t.Run("DiscountAttributeToDiscountMetaAttributes", testDiscountAttributeToManySetOpDiscountMetaAttributes)
}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {
	t.Run("DiscountToDiscountAttributes", testDiscountToManyRemoveOpDiscountAttributes)
	t.Run("DiscountAttributeToDiscountMetaAttributes", testDiscountAttributeToManyRemoveOpDiscountMetaAttributes)
}

func TestReload(t *testing.T) {
	t.Run("Discounts", testDiscountsReload)
	t.Run("DiscountAttributes", testDiscountAttributesReload)
	t.Run("DiscountMetaAttributes", testDiscountMetaAttributesReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("Discounts", testDiscountsReloadAll)
	t.Run("DiscountAttributes", testDiscountAttributesReloadAll)
	t.Run("DiscountMetaAttributes", testDiscountMetaAttributesReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("Discounts", testDiscountsSelect)
	t.Run("DiscountAttributes", testDiscountAttributesSelect)
	t.Run("DiscountMetaAttributes", testDiscountMetaAttributesSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("Discounts", testDiscountsUpdate)
	t.Run("DiscountAttributes", testDiscountAttributesUpdate)
	t.Run("DiscountMetaAttributes", testDiscountMetaAttributesUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("Discounts", testDiscountsSliceUpdateAll)
	t.Run("DiscountAttributes", testDiscountAttributesSliceUpdateAll)
	t.Run("DiscountMetaAttributes", testDiscountMetaAttributesSliceUpdateAll)
}
