// Code generated by SQLBoiler 4.4.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Discounts", testDiscountsUpsert)

	t.Run("DiscountAttributes", testDiscountAttributesUpsert)

	t.Run("DiscountMetaAttributes", testDiscountMetaAttributesUpsert)
}
